@echo off
echo Iniciando WebSAP en modo produccion...
cd C:\www\websap
echo Instalando dependencias...
call npm install --production
echo Iniciando aplicacion con Caddy...
node scripts\start-production.js
pause